# Generated by Django 3.1 on 2020-08-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_auto_20200816_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_elibator',
            new_name='is_elivator',
        ),
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
